import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
}

export default function RootLayout({ children } : Readonly<RootLayoutProps>) {
  return (
    <html
      lang="pt-br"
      className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}